"use client";
import { useCallback, useEffect, useRef, useState } from "react";

type Command = "forward" | "backward" | "left" | "right" | "stop";
type State = "CONNECTED" | "DISCONNECTED" | "ACTIVE" | "INACTIVE";
const commandName: Record<Command, string> = { forward: "FORWARD", backward: "BACKWARD", left: "LEFT", right: "RIGHT", stop: "STOP" };
const gestureMap: Record<number, Command> = { 1: "forward", 2: "backward", 3: "right", 4: "left", 5: "stop" };
const Dot = ({ good }: { good: boolean }) => <i className={good ? "dot on" : "dot"} />;

export function ConnectionStatus({ backend, ws, camera }: { backend: State; ws: State; camera: State }) {
  return <section className="panel"><p className="eyebrow">SYSTEM LINK</p>{[["PC BACKEND", backend], ["ROBOT", ws === "CONNECTED" ? "CONNECTED" : "DISCONNECTED"], ["WEBSOCKET", ws], ["CAMERA", camera]].map(([name, state]) => <p className="row" key={name}><span>{name}</span><b><Dot good={state === "CONNECTED" || state === "ACTIVE"} />{state}</b></p>)}</section>;
}
export function GestureReference() { return <section className="panel reference"><p className="eyebrow">GESTURE REFERENCE</p>{[["1 ☝", "FORWARD"], ["2 ✌", "BACKWARD"], ["3", "RIGHT"], ["4", "LEFT"], ["5", "STOP"]].map(([a, b]) => <p key={b}><span>{a}</span><b>{b}</b></p>)}</section>; }
export function SpeedControl({ speed, change }: { speed: number; change: (n: number) => void }) { return <section className="panel"><p className="eyebrow">MOTION LIMIT</p><p className="speed">MOTOR SPEED: <b>{speed}</b> steps/s</p><input aria-label="Motor speed" type="range" min="100" max="1000" step="25" value={speed} onChange={e => change(+e.target.value)} /><small>100 SAFE <em>1000 MAX</em></small></section>; }
export function ManualControlPad({ enabled, run }: { enabled: boolean; run: (c: Command) => void }) {
  const Button = ({ command, hotkey }: { command: Command; hotkey: string }) => <button disabled={!enabled} className={command === "stop" ? "pad stop" : "pad"} onClick={() => run(command)}>{commandName[command]}<kbd>{hotkey}</kbd></button>;
  return <section className="panel manual"><p className="eyebrow">MANUAL CONTROL <span>{enabled ? "KEYBOARD ENABLED" : "WAITING FOR WEBSOCKET"}</span></p><div className="pad-grid"><i/><Button command="forward" hotkey="W"/><i/><Button command="left" hotkey="A"/><Button command="stop" hotkey="X"/><Button command="right" hotkey="D"/><i/><Button command="backward" hotkey="S"/><i/></div><small>SPACE = EMERGENCY STOP</small></section>;
}
export function VoiceControl({ enabled, listen, listening, transcript }: { enabled: boolean; listen: () => void; listening: boolean; transcript: string }) { return <section className="panel voice"><p className="eyebrow">VOICE CONTROL <span>{listening ? "LISTENING" : enabled ? "READY" : "WEBSOCKET REQUIRED"}</span></p><button disabled={!enabled} onClick={listen}>{listening ? "● LISTENING…" : "🎙 START VOICE CONTROL"}</button><small>Say “forward”, “backward”, “left”, “right”, or “stop”.</small>{transcript && <p>HEARD: {transcript}</p>}</section>; }
export function RobotTelemetry({ command, speed }: { command: Command; speed: number }) { const rows = [["LEFT MOTOR", "IDLE"], ["RIGHT MOTOR", "IDLE"], ["MOTOR SPEED", `${speed} steps/s`], ["BATTERY", "— V"], ["IMU", "NOT AVAILABLE"], ["LiDAR", "NOT AVAILABLE"], ["CURRENT COMMAND", commandName[command]], ["WS LATENCY", "— ms"]]; return <section className="panel telemetry"><p className="eyebrow">ROBOT TELEMETRY <span>PLACEHOLDER DATA</span></p><div>{rows.map(([a, b]) => <p key={a}><small>{a}</small><b className={b === "STOP" ? "amber" : ""}>{b}</b></p>)}</div><small>Sensor values are unavailable until supplied by the local backend.</small></section>; }

export function TBotDashboard() {
  const video = useRef<HTMLVideoElement>(null), socket = useRef<WebSocket | null>(null);
  const [backend, setBackend] = useState<State>("DISCONNECTED"), [ws, setWs] = useState<State>("DISCONNECTED"), [camera, setCamera] = useState<State>("INACTIVE"), [command, setCommand] = useState<Command>("stop"), [speed, setSpeed] = useState(500), [fingers, setFingers] = useState<number | null>(null), [confidence, setConfidence] = useState(96), [emergency, setEmergency] = useState(false), [logs, setLogs] = useState<string[]>(["Awaiting PC backend"]), [listening, setListening] = useState(false), [transcript, setTranscript] = useState("");
  const log = useCallback((message: string) => setLogs(items => [`${new Date().toLocaleTimeString()} ${message}`, ...items].slice(0, 5)), []);
  const send = useCallback((next: Command) => { if (socket.current?.readyState === WebSocket.OPEN) socket.current.send(JSON.stringify({ command: next, speed })); }, [speed]);
  const run = useCallback((next: Command) => { if (next !== "stop" && ws !== "CONNECTED") { log("Movement blocked: WebSocket unavailable"); return; } setEmergency(false); setCommand(next); send(next); log(`Command: ${commandName[next]}`); }, [log, send, ws]);
  const emergencyStop = useCallback(() => { send("stop"); setCommand("stop"); setEmergency(true); log("EMERGENCY STOP activated"); }, [log, send]);
  useEffect(() => {
    const configured = process.env.VITE_ROBOT_WS_URL;
    const url = configured || `ws://${window.location.hostname}:8000/ws`;
    const test = url.replace(/^ws/, "http").replace(/\/ws$/, "/test");
    fetch(test).then(r => { if (!r.ok) throw Error(); setBackend("CONNECTED"); log("PC backend connected"); }).catch(() => setBackend("DISCONNECTED"));
    const link = new WebSocket(url); socket.current = link;
    link.onopen = () => { setWs("CONNECTED"); log("WebSocket connected"); };
    link.onclose = () => { setWs("DISCONNECTED"); setCommand("stop"); log("WebSocket disconnected — stopped"); };
    link.onerror = () => setWs("DISCONNECTED");
    return () => link.close();
  }, [log]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if ((e.target as HTMLElement).tagName === "INPUT") return; const map: Record<string, Command> = { w: "forward", s: "backward", a: "left", d: "right", x: "stop" }; if (e.code === "Space") { e.preventDefault(); emergencyStop(); } else if (map[e.key.toLowerCase()]) run(map[e.key.toLowerCase()]); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [emergencyStop, run]);
  const startCamera = async () => { if (!window.isSecureContext) { log("Camera needs HTTPS on a phone"); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false }); if (video.current) video.current.srcObject = stream; stream.getVideoTracks().forEach(track => track.onended = emergencyStop); setCamera("ACTIVE"); log("Camera active — local processing only"); } catch { setCamera("INACTIVE"); log("Camera permission unavailable"); emergencyStop(); } };
  const mockGesture = (value: string) => { const count = +value || null; setFingers(count); if (!count || confidence < 75) emergencyStop(); else run(gestureMap[count] || "stop"); };
  const startVoice = () => { if (!window.isSecureContext) { log("Voice control needs HTTPS on a phone"); return; } const Recognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!Recognition) { log("Voice recognition is unavailable in this browser"); return; } const recognition = new Recognition(); recognition.lang = "en-US"; recognition.interimResults = false; recognition.maxAlternatives = 1; setListening(true); recognition.onresult = (event: any) => { const heard = event.results[0][0].transcript.toLowerCase(); setTranscript(heard); const next = (["forward", "backward", "left", "right", "stop"].find(word => heard.includes(word)) || "stop") as Command; run(next); }; recognition.onerror = () => log("Voice input unavailable"); recognition.onend = () => setListening(false); recognition.start(); };
  const connected = ws === "CONNECTED";
  return <main className="station"><header><div className="brand"><strong>T</strong><div><h1>MYEQUATION <b>T-BOT</b></h1><p>ROBOT CONTROL SYSTEM</p></div></div><p className="link"><Dot good={connected}/>{connected ? "LOCAL LINK ONLINE" : "LOCAL LINK OFFLINE"}</p></header><div className="safety">FAIL-SAFE ACTIVE · Movement controls unlock only after the PC WebSocket connects.</div><div className="grid"><aside><ConnectionStatus backend={backend} ws={ws} camera={camera}/><GestureReference/><SpeedControl speed={speed} change={setSpeed}/></aside><section className="center"><section className="panel camera"><div className="title"><p className="eyebrow">CAMERA / GESTURE INPUT</p><button onClick={startCamera}>{camera === "ACTIVE" ? "CAMERA ACTIVE" : "ENABLE CAMERA"}</button></div><div className="feed"><video ref={video} autoPlay muted playsInline/><i/><p>{camera === "ACTIVE" ? "LIVE LOCAL CAMERA" : "CAMERA FEED STANDBY"}<small>Video never leaves this device</small></p></div><div className="gesture">{[["HAND STATUS", fingers ? "HAND DETECTED" : "NO HAND"], ["FINGERS", fingers || "—"], ["COMMAND", commandName[command]], ["CONFIDENCE", fingers ? `${confidence}%` : "—"]].map(([a, b]) => <p key={a}><small>{a}</small><b className={b === "STOP" ? "amber" : ""}>{b}</b></p>)}</div><div className="mock"><label>DEVELOPMENT / MOCK GESTURE <select value={fingers || ""} onChange={e => mockGesture(e.target.value)}><option value="">No hand</option>{[1,2,3,4,5].map(n => <option key={n}>{n} fingers</option>)}</select></label><label>CONFIDENCE <input aria-label="Gesture confidence" type="range" min="50" max="100" value={confidence} onChange={e => setConfidence(+e.target.value)}/></label></div></section><ManualControlPad enabled={connected} run={run}/><VoiceControl enabled={connected} listen={startVoice} listening={listening} transcript={transcript}/></section><aside className="right"><RobotTelemetry command={command} speed={speed}/><section className="panel log"><p className="eyebrow">EVENT LOG</p>{logs.map((event, i) => <p key={i}><time>{event.slice(0,8)}</time>{event.slice(9)}</p>)}</section></aside></div><button className={emergency ? "estop hot" : "estop"} onClick={emergencyStop}>⚠ EMERGENCY STOP <small>{emergency ? "STOP COMMAND SENT" : "SPACE"}</small></button></main>;
}
